site_name: MeetMate
repo_url: "https://github.com/Informatik-Projekt-Kurs"
repo_name: MeetMate GitHub
theme:
  name: material
  logo: assets/logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - header.autohide
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
  palette:
    - scheme: slate
      primary: light blue
      accent: indigo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Informatik-Projekt-Kurs"  target="_blank" rel="noopener">MeetMate</a>
extra:
  analytics:
    provider: google
    property: G-03S0LQ52J8
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false

nav:
  - Home:
    - Start: index.md
    - Introduction: introduction.md

  - Architecture: architecture/
      - Project: project.md
      - Frontend: frontend.md
      - Backend: backend.md
      - Design: design.md

  - Development: development/
    - Structure: structure/
      - Frontend: frontend.md
      - Backend: backend.md
      - Design: design.md
    - Development principles: development-principles/
      - Frontend: frontend.md
      - Backend: backend.md
      - Design: design.md

  - Features: features/
    - Core Elements: core-elements.md 
    - Authentication: authentication.md
    - Security: security.md
    - Quality Assurance: quality-assurance.md

  - Deployment: deployment/
    - Services: services/
      - Frontend: frontend.md
      - Backend: backend.md
    - Structure: structure/
      - Frontend: frontend.md
      - Backend: backend.md


  - Legal Compliance: legal-compliance/
      - Overview: overview.md
      - Privacy Policy: privacy-policy.md
      - Terms of Service: terms-of-service.md
    
  - Future Enhancements: future-enhancements/